export const CAC_CATEGORIES: Record<string, string[]> = {
  "Accommodation and Food Services": [
    "Accommodation",
    "Bakery Services",
    "Brewery Services",
    "Deal In Hot Drinks",
    "Deal In Soft Drinks",
    "Deal In Wines, Drinks And Beverages",
    "Food And Beverages Services Activities",
    "Fruits / Fruit Juice Production And Sales",
    "Hotel And Hospitality",
    "Hotel Reservation Services",
    "Hotel/hospitality Services",
    "Operate Confectionery Shop",
    "Operate Fast Food Outlet",
    "Operate Restaurant And Catering Services",
    "Operate Viewing Centre"
  ],
  "Activities of Households as Employers": [
    "Activities Of Households As Employers Of Domestic Personnel",
    "Undifferentiated Goods-and Services-producing Activities Of Private Households For Own Use"
  ],
  "Administrative and Support Services": [
    "Abattoir And Meat Selling Services",
    "Administrative And Support Services Activities",
    "Automated Car Wash Services",
    "Black Smith Services",
    "Block Industry",
    "Boutique Services",
    "Car Wash Services",
    "Catering Services",
    "Clearing And Forwarding Services",
    "Cobbler Services",
    "Cold Room Services",
    "Commission Agency",
    "Cybercaf\u00e9 And Business Centre",
    "Deal In Jewelry And Accessories",
    "Domestic Support Services",
    "Driving School Services",
    "Electrical Services",
    "Employment Activities",
    "Employment Agency",
    "Errand And Home Delivery Services",
    "Events Management, General Merchandise, Wholesale And Retail Trade",
    "Farming",
    "Fashion Designing/ Tailoring Services",
    "Fire And Safety Services",
    "Frozen Foods Services",
    "General Contracts",
    "General Merchandise",
    "Gold Smiting Services",
    "Hat Making Services",
    "Industrial And Safety Equipment Services",
    "Industrial And Safety Services",
    "Industrial Chemical Services",
    "Interior/exterior Decoration Services",
    "Internet Services",
    "Laundry Services",
    "Lubricant / Oil Services",
    "Maintenance And Repair Of Refrigerator And Air Condition",
    "Manufacturer\u2019s Representation",
    "Manufacturing Services",
    "Marketing Services",
    "Medical Laboratory Services",
    "Mortuary And Funeral Services",
    "Office Administrative,office Support And Other Business Support Activities",
    "Plant And Equipment Management",
    "Plastic Manufacturing Services",
    "Plumbing Services",
    "Point Of Sale(pos) Services",
    "Printing Press",
    "Production And Sales Of Footwear",
    "Production/sales Of Ceramics And Tiles",
    "Public Relation Services",
    "Rental And Leasing Activities",
    "Rental Services",
    "Restaurant",
    "Safety Equipment Services",
    "Sale Of Petroleum Products",
    "Sales And Supply Of Iron Seals And Metals",
    "Sales Of Books And Stationeries",
    "Sawmilling Services",
    "Security And Investigation Activities",
    "Service To Building And Landscape Activities",
    "Supply Of Iron Scraps And Metals",
    "Supply Of Unskilled Labour",
    "Technical Services",
    "Textile Services",
    "Trading",
    "Travel Agency",
    "Travel Agency, Tour Operator And Other Reservation Services And Related Activities",
    "Upholstery And Furniture Making.",
    "Vulcanizing Services",
    "Welding Services",
    "Wheel Balancing And Alignment Services"
  ],
  "Agriculture, Forestry & Fishing": [
    "Agriculture Forestry & Fishing",
    "Animal Husbandry Services",
    "Aquarium Services",
    "Aviary Services",
    "Crop And Animal Production,hunting And Related Services Activities",
    "Fish Farming/aquaculture",
    "Fishing & Aquaculture",
    "Food Production And Processing Services",
    "Forestry & Logging",
    "Gardening Services",
    "Honey Processing",
    "Horticultural Services",
    "Kennel Services",
    "Livestock Feeds Production And Distribution",
    "Livestock Management Services",
    "Milling And Grinding Services",
    "Piggery Services",
    "Poultry Services",
    "Sale Of Agricultural Produce",
    "Sale Of Agricultural Tools, Machine & Allied Products",
    "Sale Of Animals",
    "Sale Of Diary Products",
    "Sale Of Groceries"
  ],
  "Arts, Entertainment and Recreation": [
    "Art Galleries, Museum And Monuments Services",
    "Artiste Management And Services",
    "Arts, Craft, And Designing",
    "Bar Services",
    "Creative, Art And Entertainment Activities",
    "Entertainment Services",
    "Events Managements/planning",
    "Gambling And Betting Activities",
    "Installation Of Cctv And Allied Products",
    "Libraries, Archives, Museums And Other Cultural Activities",
    "Modeling Services",
    "Organise Dance Class Services",
    "Painting Services",
    "Parks And Recreation Services",
    "Photography Services",
    "Sale Of Sports Equipment",
    "Sport Activities And Amusement And Recreation Activities",
    "Sport Promotion Services",
    "Stress Management Services",
    "Video Cd Rental Services"
  ],
  "Automobile Services": [
    "Automobile Repairs/mechanical Services",
    "Panel Beating/car Spraying Service",
    "Sale Of Automobile Spare Parts",
    "Sale Of Engineering Equipment, Machinery And Other Hardware",
    "Sale Of Motor Vehicle, Motorcycles And Other Automobile Products"
  ],
  "Churches and Religious Organizations": [
    "Church",
    "Churches",
    "It Others",
    "Mosque",
    "Mosques"
  ],
  "Community Associations": [
    "Community Based Association"
  ],
  "Construction": [
    "Boat And Canoe Construction",
    "Bricklaying/masonary Services",
    "Building Works",
    "Carpentry/upholstery Services",
    "Civil Engineering",
    "Construction Of Buildings",
    "Glass Works",
    "Mechanical Works",
    "Metal Works",
    "Specialized Construction Activities",
    "Steel Works Services",
    "Supply, Sale And Distribution Of Building Materials"
  ],
  "Cultural Associations": [
    "Cultural Based Association"
  ],
  "Education": [
    "Apprenticeship And Training Services",
    "Business Support/development Services",
    "Curriculum Planning/development",
    "Education",
    "Educational Services And Consultancy",
    "Feasibility Studies",
    "Guidance And Counseling Services",
    "Ict Training And Consultancy",
    "Library Services",
    "Montessori Supplies",
    "Montessori Training",
    "Operate Bible College",
    "Operate Computer Training School",
    "Operate Cr\u00e8che And Day Care",
    "Operate Islamic School",
    "Operate Nursery And Primary School",
    "Operate Primary And Secondary School",
    "Organizing Conferences",
    "Organizing Seminars/symposiums",
    "Publication Of Law Reports And Journals",
    "Teachers Recruitment",
    "Vocational Education And Training Services"
  ],
  "Energy and Power": [
    "Energy Production",
    "Hydro Electrical Work",
    "Production And Distribution Of Renewable Energy",
    "Solar Energy",
    "Supply, Sales And Services Of Solar Equipment And Inverters."
  ],
  "Extraterritorial Organizations": [
    "Activities Of Extraterritorial Organizations And Bodies"
  ],
  "Financial and Insurance Activities": [
    "Accounting / Auditing Consultancy",
    "Accounting / Auditing, Taxation And Financial Management Consultancy",
    "Activities Auxiliary To Financial Services And Insurance Activities",
    "Financial Consultancy",
    "Financial Services Activities, Except Insurance And Pension Funding",
    "Forensic Accounting Services",
    "Insurance, Reinsurance And Pension Funding, Except Compulsory Social Security.",
    "Private Equity Fund"
  ],
  "Foundations": [
    "Foundation Based Association"
  ],
  "General Business Services / Miscellaneous": [
    "Abattoir And Meat Selling Services",
    "Accounting, Auditing, Taxation And Financial Management Consultancy",
    "Accounting/auditing Consulting Services",
    "Advertisement",
    "Aeronautic Engineering",
    "Alternative Medical Practise And Consultancy",
    "Aluminium Manufacturing/works",
    "Ambulance Services",
    "Animal Husbandry Services",
    "Apprenticeship And Training Services",
    "Aquarium Services",
    "Arbitration/mediation",
    "Architectural Designs",
    "Architectural Practise And Consultancy",
    "Art Galleries, Museum, And Monuments Services",
    "Artisan",
    "Arts And Crafts",
    "Auctioneering Services",
    "Auto Repairs/mechanical Services",
    "Automated Car Wash Services",
    "Automobile Parking Services",
    "Aviation Consultancy",
    "Bakery Services",
    "Banking And Financial Consultancy",
    "Bar Services",
    "Beauty And Salon Services",
    "Blacksmithing",
    "Boat/ship Building Services/canoe",
    "Books And Stationery Stores Services",
    "Borehole Drilling",
    "Boutique Services",
    "Branding Services",
    "Brewery Services",
    "Bricklaying/mason/painting Works",
    "Building Works",
    "Bulk Sms Services",
    "Business Development Services",
    "Car Rental Services",
    "Car Wash Services",
    "Carpentry And Wood Works/upholstery Services",
    "Catering Services",
    "Chemical Emgineering Services",
    "Cinematography/theatre Services",
    "Civil Engineering Services",
    "Cleaning/waste Disposal Services",
    "Cobbler Services",
    "Cold Room Services",
    "Commission Agency",
    "Construction Works",
    "Dairy Products/services",
    "Deal In Hot Drinks",
    "Deal In Jewellery And Accessories",
    "Deal In Perfume",
    "Deal In Petrochemicals",
    "Deal In Wine Drinks And Beverages",
    "Dental/dentistry Services",
    "Digital E-learning",
    "Distillery/winery/brewery",
    "Domestic Support Services",
    "Driving School Services",
    "Drycleaning Services",
    "E-business",
    "Educational Services",
    "Electrical Engineering Services",
    "Electrical/electronic Services",
    "Employment Agency",
    "Energy Production",
    "Engineering Consultancy",
    "Entertainment Services",
    "Environmental Management Services",
    "Environmental Services/landscaping Services",
    "Estate Agency",
    "Estate And Commission Agency",
    "Estate And Facility Management",
    "Estate Surveying And Valuation",
    "Events Management",
    "Farming",
    "Fashion Designing",
    "Financial Management Consultancy",
    "Fire And Safety Services",
    "Fish Farming",
    "Food Production And Processing Services",
    "Frozen Foods Services",
    "Fruits/fruit Juice Services",
    "Fumigation/pest Control Services",
    "Gardening Services",
    "General Contract",
    "General Merchandise/procurement",
    "Geosciences Services",
    "Glass Works",
    "Gold Smithing",
    "Graphic Designing",
    "Guidance And Counselling Services",
    "Gymnasium",
    "Hat Making/millinery",
    "Haulage Services",
    "Hiring Services/equipment",
    "Home Delivery Services",
    "Honey Processing",
    "Horticulture/gardening Services",
    "Hotel Reservation Services",
    "Hotel/hospitality Services",
    "Human Resource Development And Management",
    "Hydroelectric Works",
    "Import And Export",
    "Industrial And Safety Equipment Services",
    "Industrial Chemical Services",
    "Industrial Cleaning",
    "Industrial Cleaning Services",
    "Information And Communication Technology Services",
    "Installation Of Cctv",
    "Interior And Exterior Decoration",
    "Internet Services",
    "Janitorial Services",
    "Laboratory Services",
    "Land Surveying And Valuation",
    "Landscaping Services",
    "Laundry And Drycleaning Services",
    "Leather Works/tannery",
    "Legal Practice And Consultancy",
    "Legal Practice/consultancy",
    "Library Services",
    "Livestock Feeds/management",
    "Loading And Off Loading Of General Goods",
    "Lubricant Oil/services",
    "Maintenance Of Refridgerators And Airconditioners",
    "Make Up Artistry",
    "Makeover Services",
    "Management Consultancy/services",
    "Manicure And Pedicure Services",
    "Manufacturer\u2019s Representation",
    "Manufacturing And Sale Of Carpet",
    "Manufacturing Of Bags",
    "Manufacturing Of Plastic Products",
    "Manufacturing Services",
    "Manufacturing, Distribution And Sale Of Textile Materials",
    "Manufacturing/production And Sale Of Cosmetics",
    "Marine Transportation",
    "Marketing Services",
    "Mechanical Engineering",
    "Mechanical Works",
    "Media Services",
    "Medical Laboratory Services",
    "Medical Practice And Consultancy",
    "Metal Works/fabrication",
    "Mid-wifery Services",
    "Milling/grinding Services",
    "Mining/quarry Services",
    "Modelling Services",
    "Mortician/funeral Home Services",
    "Music And Film Production",
    "Music Production",
    "Newspaper And Magazine Services",
    "Oil And Gas Services",
    "Oil Field Servicing",
    "On-line Alternative Dispute Resolution",
    "Online Fashion Services",
    "Operate Art Galleries/museum",
    "Operate Bakery/confectionery",
    "Operate Bar",
    "Operate Bible College",
    "Operate Block Moulding Industry",
    "Operate Bookshops/stationery Stores",
    "Operate Boutique/fashion House",
    "Operate Butchery/abattoir",
    "Operate Clinic/maternity Home",
    "Operate Community Health Centre",
    "Operate Computer Training School",
    "Operate Creche And Daycare",
    "Operate Cyber Caf\u00e9 And Business Centre",
    "Operate Departmental Stores",
    "Operate Dispensary",
    "Operate Driving School",
    "Operate Fast Food Outlet",
    "Operate Hair & Beauty Saloon",
    "Operate Hospital/clinic",
    "Operate Islamic School",
    "Operate Maternity Clinic",
    "Operate Nursery And Primary School",
    "Operate Nursery School",
    "Operate Nursery, Primary And Secondary School",
    "Operate Parks And Recreation Centre",
    "Operate Patent Medicine Store",
    "Operate Perfumery",
    "Operate Pharmacy",
    "Operate Primary School",
    "Operate Printing Press",
    "Operate Secondary School",
    "Operate Spa/beauty Clinic",
    "Operate Supermarket",
    "Operate Viewing Centre",
    "Ophalmological/eye Clinic Services",
    "Optical Equipment Services",
    "Organising Dance Class Services",
    "Other Activities Of Extra-territorial Organization And Bodies",
    "Outsourcing Services",
    "Oversea Student Admission/placement Services",
    "Painting Services",
    "Panel Beating Services",
    "Patent Medicine Services",
    "Photography",
    "Physiotherapy Services",
    "Piggery Services",
    "Plastic Manufacturing Services",
    "Plumbing Works",
    "Poultry",
    "Poultry/farming",
    "Printing",
    "Private Equity Fund",
    "Production & Processing Of Palm Oil",
    "Production & Sale Of Tiles, Ceramic And Marbles",
    "Production And Processing Of Food",
    "Production And Sale Of Footwear",
    "Production And Sale Of Paint",
    "Production And Sale Of Polythene Bags",
    "Production And Sale Of Stationery/books",
    "Production, Distribution & Sale Of Bottled And Packaged Water",
    "Production, Processing & Sale Of Fruits And Fruit Juice",
    "Production, Processing And Sale Of Soap",
    "Production, Sale And Installation Of Electrical And Electronic Equipment",
    "Production, Sale And Renting Of Video / Cd",
    "Production, Sale And Servicing Of Electronics",
    "Production. Distributon And Sale Of Packaged Water",
    "Project Management",
    "Property Development",
    "Property Management",
    "Public Convenience Services",
    "Public Relations",
    "Publishing Of Books",
    "Publishing Of Magazines And Journals",
    "Publishing Of Newspaper",
    "Quantity Surveying",
    "Recycling Services",
    "Rental Services",
    "Road Transportation",
    "Sale & Servicing Of Computer Equipment And Accessories",
    "Sale & Servicing Of Industrial And Safety Equipment",
    "Sale & Servicing Of Telephone And Accessories",
    "Sale And Manufacturing Of Cosmetics",
    "Sale Of Agricultural Produce",
    "Sale Of Agricultural Tools, Machines &allied Products",
    "Sale Of Automobile And Spare Parts",
    "Sale Of Sport Equipment",
    "Sale Of Telecommunication Equipment And Accessories",
    "Sale Of Veterinary Drugs And Equipment",
    "Sale Ofbicycles And Spare Parts",
    "Sale Ofbuilding Materials",
    "Sale Offire And Safety Equipment",
    "Sale Ofgrocery",
    "Sale, Supply And Distribution Of Petroleum Products",
    "Sale, Supply And Servicing Of Laboratory Equipment",
    "Servicing Of Safety Equipment",
    "Shoemaking/cobbling",
    "Social Networking Services",
    "Software Development/web Designing",
    "Sport Promotion",
    "Steel Works/fabrication",
    "Stress Management Services",
    "Student Admission Placement Services",
    "Supply Of Industrial Chemicals",
    "Supply Of Iron Scraps And Metals",
    "Supply Of Unskilled Labour Services",
    "Tailoring Services",
    "Tax Consulting",
    "Technical Services",
    "Town Planning",
    "Trading",
    "Transportation Services",
    "Upholsteryand Furniture Making",
    "Veterinary Practice And Consultancy",
    "Vocational Education And Training Services",
    "Vulcanizing",
    "Waste Disposal And Recycling Services",
    "Water Production And Packaging Services",
    "Welding Services",
    "Wheel Balancing And Alignment Services"
  ],
  "Human Health and Social Work": [
    "Ambulance Services",
    "Beauty And Salon Services",
    "Chemist/nursing Home",
    "Dental Practice And Services",
    "Fumigation And Pest Control Services",
    "Gymnasium Services",
    "Human Health Activities",
    "Make Up And Makeover Services",
    "Operate Community Health Care Centre",
    "Operate Hospital / Clinic",
    "Operate Maternity Clinic",
    "Optical Services",
    "Patent /medicine Services",
    "Pedicure And Manicure Services",
    "Perfumery Services",
    "Physiotherapy Services",
    "Public Convenience Services",
    "Residential Care Activities",
    "Sale Of Veterinary Equipment And Drugs",
    "Sales And Supply Of Hospital Optical And Laboratory Equipment",
    "Social Work Activities Without Accommodation",
    "Spa Treatment Services",
    "Traditional Medicine",
    "Veterinary Services"
  ],
  "Information and Communication": [
    "Advertising And Marketing Services",
    "Bulk Sms Services",
    "Cinematography / Theaters Services",
    "Computer Programming, Consultancy And Related Activities",
    "Graphic Designing",
    "Information Service Activities",
    "Motion Picture, Video And Television Programme Production, Sound Recording And Music Publishing Activities",
    "Networking Services",
    "Programmimg And Broadcasting Activities",
    "Publishing Activities",
    "Software Development, Web Design And Intranet Development",
    "Supply Of Hardware",
    "Telecommunications"
  ],
  "Manufacturing": [
    "Aluminum Manufacturing, Works, Sales And Fittings",
    "Electricity,gas,stream & Air Conditioning Supply",
    "Leather Works/tannery Services",
    "Manufacture Of Basic Metals",
    "Manufacture Of Basic Pharmaceutical Products And Pharmaceutical Preparations",
    "Manufacture Of Beverages",
    "Manufacture Of Chemicals And Chemical Products",
    "Manufacture Of Coke And Refined Petroleum Products",
    "Manufacture Of Computer, Electronic And Optical Products",
    "Manufacture Of Electrical Equipment",
    "Manufacture Of Fabricated Metal Products, Except Machinery And Equipment",
    "Manufacture Of Food Products",
    "Manufacture Of Furniture",
    "Manufacture Of Leather And Related Products",
    "Manufacture Of Machinery And Equipment N.e,c",
    "Manufacture Of Motor Vehicles, Trailers And Semi-trailers",
    "Manufacture Of Other Non-metallic Material Products",
    "Manufacture Of Other Transport Equipment",
    "Manufacture Of Paper And Paper Products",
    "Manufacture Of Rubber And Plastic Products",
    "Manufacture Of Textiles",
    "Manufacture Of Tobacco Products",
    "Manufacture Of Wearing Apparel",
    "Manufacture Of Wood And Of Products Of Wood And Cook,expect Furniture;manufacture Of Article Of Straw And Plaiting Material",
    "Manufacturing Of Candles And Associated Products",
    "Manufacturing Of Plastic Products",
    "Other Manufacturing",
    "Printing And Reproduction Of Recorded Media",
    "Production And Sale Of Bottled And Packed Water",
    "Production And Sale Of Cooking Or Edible Oil",
    "Production And Sale Of Polythene Bags",
    "Production And Sale Of Tiles And Ceramic Products",
    "Production, Supply, Sale And Installation Of Electrical And Electronic Equipment",
    "Repair And Installation Of Machinery And Equipment",
    "Sale And Manufacturing Cosmetics",
    "Sale And Manufacturing Of Carpets",
    "Sale And Production Of Foot Wares"
  ],
  "Mining and Quarrying": [
    "Extraction Of Crude Petroleum And Natural Gas",
    "Geosciences Services",
    "Mining And Grinding Services",
    "Mining And Quarrying",
    "Mining Of Coal And Lignite",
    "Mining Of Metal Ores",
    "Mining Support Services Activities",
    "Oil And Gas Services",
    "Other Mining And Quarrying"
  ],
  "Other Service Activities": [
    "Activities Of Membership Organizations",
    "Advertisement",
    "Apprenticeship/training Services",
    "Automobile Towing Services",
    "Automobile/mechanical Services",
    "Beauty Pageants",
    "Fashion Design,tailoring Services",
    "Film Production Services",
    "Music Production",
    "Other Personal Services Activities",
    "Other Service Activities",
    "Radio And Television Services",
    "Recycling Services",
    "Repair Of Computers And Personal And Household Goods",
    "Sale And Distribution Of Textile Materials",
    "Sale And Supply Of Cameras, Projectors, And Photography Accessories",
    "Sale Of Computer, Laptops, Printers, Photocopies And Their Accessories",
    "Sale Of Fire And Safety Equipment",
    "Sale Of Mobile Phones And Accessories",
    "Sale Of Sim Cards, Credit/recharge Cards",
    "Sale Of Telecommunication Accessories",
    "Sale/distribution Of Petroleum Products",
    "Sales Of Automobiles And Spare Parts",
    "Student Admission Placement Services"
  ],
  "Professional, Scientific and Technical Activities": [
    "Accounting And Auditing Consultancy",
    "Activities Of Head Officies;management Consultancy Activities",
    "Advertising And Market Research",
    "Aeronautic Engineering/consultancy",
    "Agricultural Engineering",
    "Arbitration/mediation Services",
    "Architectural And Engineering Activities; Technical Testing And Analysis",
    "Architectural Practice And Consultancy",
    "Auctioneering Services",
    "Chemical Engineering Services",
    "Civil Engineering Services",
    "Clinic And Maternity Home",
    "Community Health Center",
    "Company Liquidation Services",
    "Company Secretarial Services",
    "Electrical Engineering Services",
    "Engineering Services",
    "Human Resources Management And Development Services",
    "Laboratory Services",
    "Legal And Accounting Activities",
    "Legal Practice And Consultancy",
    "Legislative Consultancy",
    "Management Consultancy Services",
    "Medical Practice And Consultancy",
    "Midwifery Services",
    "Other Professional,scientific And Technical Activities",
    "Pharmaceutical Services",
    "Physiotherapy Services",
    "Quantity Surveying",
    "Radiography And General Body Language Services.",
    "Scientific Research And Development",
    "Tax Consultancy",
    "Verterinary Activities"
  ],
  "Public Administration": [
    "Public Administration And Defence; Complusory Social Security"
  ],
  "Real Estate Activities": [
    "Environmental And Landscaping Services",
    "Estate Agency",
    "Estate And Facility Management",
    "Estate Surveying And Valuation",
    "Project Management Services",
    "Property Development Services",
    "Property Management Services",
    "Real Estate Activities",
    "Real Estate Activities.",
    "Town Planning Services"
  ],
  "Social Clubs": [
    "Social Clubs Based Association"
  ],
  "Sporting Associations": [
    "Sporting Based Association"
  ],
  "Transportation and Storage": [
    "Air Transport",
    "Land Transport And Transport Via Pipelines",
    "Postal And Courier Activities",
    "Rail And Tramp Services",
    "Road Transportation Services",
    "Sea Transport",
    "Transportation",
    "Truck And Haulage Services",
    "Warehousing And Support Activities For Tranportation",
    "Water Transport"
  ],
  "Water Supply, Sewerage & Waste Management": [
    "Borehole Drilling And Water Works",
    "Cleaning/waste Disposal Services",
    "Industrial Cleaning Services",
    "Laundry And Dry Cleaning Services",
    "Remediation Activities And Other Waste Management Services",
    "Sewerage",
    "Waste Collection, Treatment And Disposal Activities: Material Recovery",
    "Water Collection Treatment And Supply"
  ],
  "Wholesale and Retail Trade": [
    "Deal In General Goods And Manufacturers Representatives",
    "Import And Export Of General Goods",
    "Operate Departmental Stores",
    "Operate Supermarkets",
    "Retail Trade, Except Of Motor Vehicle And Motorcycles.",
    "Supply And Distribution Of General Goods",
    "Wholesale And Retail Trade And Repair Of Motor Vechicles And Motorcycles.",
    "Wholesale Trade, Except Of Motor Vehicle And Motorcycle."
  ]
};